general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita lanzar múltiples instancias de hyprlock
    before_sleep_cmd = loginctl lock-session    # Bloquea la pantalla antes de suspender
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # Asegura encender la pantalla al despertar
}

# 1. Bajar brillo a los 5 minutos
listener {
    timeout = 300
    on-timeout = brightnessctl set 10%-
    on-resume = brightnessctl set 10%+
}

# 2. Bloquear pantalla a los 10 minutos
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 3. Apagar pantalla (DPMS OFF) a los 11 minutos
listener {
    timeout = 660
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}
