general {
    grace = 2
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot   # Toma una captura de tu pantalla actual y la usa de fondo
    blur_passes = 3     # Efecto difuminado (estilo cristal esmerilado)
    blur_size = 8
    color = rgba(25, 20, 20, 1.0)
}

# RELOJ
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(242, 243, 244, 0.75)
    font_size = 95
    font_family = JetBrains Mono Extrabold
    position = 0, 200
    halign = center
    valign = center
}

# CAMPO DE CONTRASEÑA
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Tamaño de los puntos de la contraseña
    dots_spacing = 0.35 # Espaciado de los puntos
    dots_center = true
    outer_color = rgba(242, 243, 244, 0.1)
    inner_color = rgba(25, 20, 20, 0.5)
    font_color = rgb(242, 243, 244)
    fade_on_empty = true # Oculta el cuadro si no estás escribiendo (Ultra minimal)
    fade_timeout = 1000
    placeholder_text = <i>Ingresa contraseña...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}
