listener {
    timeout = 300                                 # 5 minutos
    on-timeout = brightnessctl set 10%-           # Baja el brillo de la pantalla
    on-resume = brightnessctl set 10%+            # Recupera el brillo al mover el mouse
}

listener {
    timeout = 600                                 # 10 minutos
    on-timeout = hyprlock                         # Lanza el bloqueador de pantalla
}

listener {
    timeout = 660                                 # 11 minutos (un poco después de bloquear)
    on-timeout = hyprctl dispatch dpms off        # Apaga la pantalla por completo para ahorrar energía
    on-resume = hyprctl dispatch dpms on          # Enciende la pantalla al mover el mouse
}
